name: Poll External Repo and Deploy

on:
  schedule:
    - cron: "0 0 * * *" # Check for updates once every day
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  poll-external-repo:
    runs-on: ubuntu-latest
    env:
      EXTERNAL_REPO: Hiro420/StellaSoraData
    outputs:
      changed: ${{ steps.check_commit.outputs.changed }}

    steps:
      - name: Checkout this repo so we can call other workflow
        uses: actions/checkout@v3

      - name: Get latest commit from external repo
        id: get_commit
        run: |
          echo "Fetching latest commit from $EXTERNAL_REPO..."
          response=$(curl -s -w "%{http_code}" -o latest_commit.json https://api.github.com/repos/$EXTERNAL_REPO/commits)
          status_code="${response: -3}"
          if [ "$status_code" != "200" ]; then
            echo "Error: Received HTTP $status_code"
            exit 1
          fi
          latest_commit=$(jq -r '.[0].sha' latest_commit.json)
          echo "latest_commit=$latest_commit" >> $GITHUB_OUTPUT

      - name: Restore last commit cache
        uses: actions/cache@v3
        with:
          path: last-commit
          key: last-commit-cache-${{ steps.get_commit.outputs.latest_commit }}
          restore-keys: last-commit-cache
        continue-on-error: true

      - name: Check if commit has changed
        id: check_commit
        run: |
          if [ -f last-commit ]; then
            old_commit=$(cat last-commit)
            if [ "$old_commit" = "${{ steps.get_commit.outputs.latest_commit }}" ]; then
              echo "No new commit. Exiting."
              echo "changed=false" >> $GITHUB_OUTPUT
              exit 0
            fi
          fi
          echo "${{ steps.get_commit.outputs.latest_commit }}" > last-commit
          echo "changed=true" >> $GITHUB_OUTPUT

      - name: Save last commit cache
        uses: actions/cache@v3
        with:
          path: last-commit
          key: last-commit-cache-${{ steps.get_commit.outputs.latest_commit }}

  trigger-deploy:
    needs: poll-external-repo
    if: needs.poll-external-repo.outputs.changed == 'true'
    uses: ./.github/workflows/cicd.yml
